baseURL = "https://rodogi.github.io"
languageCode = "en-us"
title = "Rodrigo Dorantes Gilardi"
theme = "codex"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[logger]
  level = "WARN"
  ignoreLogs = ['warning-goldmark-raw-html']

[params]
  twitter = "https://twitter.com/ruydg"
  github = "https://github.com/rodogi"
  scholar = "https://scholar.google.com/citations?user=Qe5ab4gAAAAJ&hl=en"
  iconOrder = ["twitter", "github", "scholar"]

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Research"
  url = "/research"
  weight = 2

  [[menu.main]]
  name = "CV"
  url = "/resume/resume.pdf"
  weight = 3